version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: tilda-backend
    ports:
      - "8080:8080"
    environment:
      # Настройки для Spring Boot
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tilda-test-server
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: tilda-db
    environment:
      POSTGRES_DB: tilda-test-server
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
